/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views;

import com.client.manager.constants.WindowSize;
import com.client.manager.Application;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Giang
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setIconImage(Application.ICON);
        initContext();
        setSize(WindowSize.WIDE_WINDOW.getDimension());
        setMinimumSize(WindowSize.TINY_WINDOW.getDimension());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        scrViewPort = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm - Dành cho Quản lý");

        pnlViewPort.setLayout(new java.awt.CardLayout());
        scrViewPort.setViewportView(pnlViewPort);

        jMenu1.setText("Lớp học");

        jMenuItem1.setText("Các khối");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Các lớp");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Thêm lớp");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Giáo viên");

        jMenuItem4.setText("Danh sách giáo viên");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Thêm giáo viên");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator2);

        jMenuItem6.setText("Tài khoản giáo viên");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Học sinh");

        jMenu8.setText("Danh sách học sinh");
        jMenu3.add(jMenu8);

        jMenuItem7.setText("Thêm học sinh");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Hệ thống");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Đóng ứng dụng Web");
        jMenu5.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Đóng ứng dụng giáo viên");
        jMenu5.add(jCheckBoxMenuItem2);
        jMenu5.add(jSeparator3);

        jMenuItem8.setText("Thông tin trường học");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Thuộc tính hệ thống");
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Tài khoản");

        jMenuItem10.setText("Tài khoản Quản lý");
        jMenu6.add(jMenuItem10);

        jMenuItem11.setText("Tài khoản Giáo viên");
        jMenu6.add(jMenuItem11);
        jMenu6.add(jSeparator4);

        jMenuItem12.setText("Tài khoản của tôi");
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Hỗ trợ");

        jMenuItem13.setText("Hướng dẫn sử dụng");
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("Giới thiệu");
        jMenu7.add(jMenuItem14);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewPort, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    static final javax.swing.JPanel pnlViewPort = new javax.swing.JPanel();
    private javax.swing.JScrollPane scrViewPort;
    // End of variables declaration//GEN-END:variables

    private void initContext() {
        JMenuItem mni;
        // Title bar & Windows
        if (Application.ACCOUNT != null) {
            setTitle(getTitle() + " [" + Application.ACCOUNT.getId()+ "]");
        }
        setLocationRelativeTo(null);
    }

    static void setViewPort(JPanel panel) {
        pnlViewPort.setVisible(false);
        pnlViewPort.removeAll();
        pnlViewPort.add(panel);
        pnlViewPort.repaint();
        pnlViewPort.revalidate();
        pnlViewPort.updateUI();
        pnlViewPort.setVisible(true);
    }
}
