/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views;

import com.client.manager.constants.WindowSize;
import com.client.manager.Application;
import com.client.manager.constants.ConfirmOption;
import com.client.manager.constants.WebMethods;
import com.client.manager.constants.WindowUtility;
import com.client.manager.views.account.AccountPasswordFrame;
import com.client.manager.views.account.AdminAccountFrame;
import com.client.manager.views.classes.AddClassFrame;
import com.client.manager.views.classes.ClassBulkFrame;
import com.client.manager.views.student.AddStudentFrame;
import com.client.manager.views.student.StudentFrame;
import com.client.manager.views.system.SchoolInfoFrame;
import com.client.manager.views.system.SystemInfoFrame;
import com.client.manager.views.system.TeacherAccountFrame;
import com.client.manager.views.teacher.AddTeacherFrame;
import com.client.manager.views.teacher.TeacherInfoFrame;
import com.client.service.Properties;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Giang
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setIconImage(Application.ICON);
        initContext();
        setSize(WindowSize.WIDE_WINDOW.getDimension());
        setMinimumSize(WindowSize.TINY_WINDOW.getDimension());
        setLocationRelativeTo(null);
        applyRealms();
        setViewPort(new WelcomeFrame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        scrViewPort = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClass = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnuTeacher = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuStudent = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        chkWeb = new javax.swing.JCheckBoxMenuItem();
        chkApp = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mniAdminAccount = new javax.swing.JMenuItem();
        mniTeacherAccount = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm - Dành cho Quản lý");

        pnlViewPort.setLayout(new java.awt.CardLayout());
        scrViewPort.setViewportView(pnlViewPort);

        mnuClass.setText("Lớp học");

        jMenuItem1.setText("Các khối");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuClass.add(jMenuItem1);
        mnuClass.add(jSeparator1);

        jMenuItem2.setText("Các lớp");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuClass.add(jMenuItem2);

        jMenuItem3.setText("Thêm lớp");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuClass.add(jMenuItem3);
        mnuClass.add(jSeparator5);

        jMenuItem15.setText("Môn học");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mnuClass.add(jMenuItem15);

        jMenuBar1.add(mnuClass);

        mnuTeacher.setText("Giáo viên");

        jMenuItem4.setText("Danh sách giáo viên");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuTeacher.add(jMenuItem4);

        jMenuItem5.setText("Thêm giáo viên");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuTeacher.add(jMenuItem5);
        mnuTeacher.add(jSeparator2);

        jMenuItem6.setText("Tài khoản giáo viên");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuTeacher.add(jMenuItem6);

        jMenuBar1.add(mnuTeacher);

        mnuStudent.setText("Học sinh");

        jMenuItem17.setText("Danh sách học sinh");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        mnuStudent.add(jMenuItem17);

        jMenuItem7.setText("Thêm học sinh");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuStudent.add(jMenuItem7);

        jMenuBar1.add(mnuStudent);

        mnuAdmin.setText("Hệ thống");

        chkWeb.setText("Đóng ứng dụng Web");
        chkWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWebActionPerformed(evt);
            }
        });
        mnuAdmin.add(chkWeb);

        chkApp.setText("Đóng ứng dụng giáo viên");
        chkApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAppActionPerformed(evt);
            }
        });
        mnuAdmin.add(chkApp);
        mnuAdmin.add(jSeparator3);

        jMenuItem8.setText("Thông tin trường học");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuAdmin.add(jMenuItem8);

        jMenuItem9.setText("Thuộc tính hệ thống");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnuAdmin.add(jMenuItem9);

        jMenuBar1.add(mnuAdmin);

        jMenu6.setText("Tài khoản");

        mniAdminAccount.setText("Tài khoản Quản lý");
        mniAdminAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdminAccountActionPerformed(evt);
            }
        });
        jMenu6.add(mniAdminAccount);

        mniTeacherAccount.setText("Tài khoản Giáo viên");
        mniTeacherAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTeacherAccountActionPerformed(evt);
            }
        });
        jMenu6.add(mniTeacherAccount);
        jMenu6.add(jSeparator4);

        jMenuItem12.setText("Tài khoản của tôi");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);
        jMenu6.add(jSeparator6);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Đăng xuất");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Hỗ trợ");

        jMenuItem13.setText("Hướng dẫn sử dụng");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("Giới thiệu");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewPort, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setViewPort(new ClassBulkFrame(0));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setViewPort(new ClassBulkFrame(1));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AddClassFrame.showDialog(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        setViewPort(new TeacherInfoFrame());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AddTeacherFrame.showDialog(this);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        setViewPort(new TeacherAccountFrame());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        AddStudentFrame.showDialog(this);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void chkWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWebActionPerformed
        // TODO add your handling code here:
        if (chkWeb.isSelected()) {
            // User wants to check
            ConfirmOption conf = WindowUtility.showConfirm(mnuClass, "Vô hiệu hóa website xem điểm", "Phụ huynh và học sinh sẽ không thể sử dụng website xem điểm.\nBạn có chắc chắn?");
            if (conf.equals(ConfirmOption.YES)) {
                Properties p = new Properties();
                p.setKey("web_status");
                p.setValue("0");
                new Thread(() -> {
                    WebMethods.updateProperty(p);
                }).start();
            } else {
                chkWeb.setSelected(false);
            }
        } else {
            // User wants to uncheck
            Properties p = new Properties();
            p.setKey("web_status");
            p.setValue("1");
            new Thread(() -> {
                WebMethods.updateProperty(p);
            }).start();
        }
    }//GEN-LAST:event_chkWebActionPerformed

    private void chkAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAppActionPerformed
        // TODO add your handling code here:
        if (chkApp.isSelected()) {
            // User wants to check
            ConfirmOption conf = WindowUtility.showConfirm(mnuClass, "Vô hiệu hóa ứng dụng giáo viên", "Giáo viên sẽ khoogn thể đăng nhập ứng dụng nhập điểm.\nBạn có chắc chắn?");
            if (conf.equals(ConfirmOption.YES)) {
                Properties p = new Properties();
                p.setKey("app_status");
                p.setValue("0");
                new Thread(() -> {
                    WebMethods.updateProperty(p);
                }).start();
            } else {
                chkApp.setSelected(false);
            }
        } else {
            // User wants to uncheck
            Properties p = new Properties();
            p.setKey("app_status");
            p.setValue("1");
            new Thread(() -> {
                WebMethods.updateProperty(p);
            }).start();
        }
    }//GEN-LAST:event_chkAppActionPerformed

    private void mniTeacherAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTeacherAccountActionPerformed
        // TODO add your handling code here:
        setViewPort(new TeacherAccountFrame());
    }//GEN-LAST:event_mniTeacherAccountActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        setViewPort(new SchoolInfoFrame());
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        setViewPort(new SystemInfoFrame());
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mniAdminAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdminAccountActionPerformed
        // TODO add your handling code here:
        setViewPort(new AdminAccountFrame());
    }//GEN-LAST:event_mniAdminAccountActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        setViewPort(new AccountPasswordFrame());
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        StringBuilder msg = new StringBuilder();
        msg.append("Quản lý điểm\nPhần quản lý\n\nPhiên bản 1.0-M\n\n")
                .append("Người thực hiện:\n")
                .append("Nguyễn Bằng Giang; Phạn Xuân Đức; Lê Tiến Đạt, Ứng Đình Hướng; Nguyễn Phương Nam\n\n")
                .append("Icon: PAOmedia");
        JOptionPane.showMessageDialog(this, msg.toString(), "Giới thiệu", JOptionPane.DEFAULT_OPTION, new ImageIcon(Application.ICON));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        setViewPort(new ClassBulkFrame(2));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        int ch = WindowUtility.showConfirm(this, "Đăng xuất", "Bạn có thực sự muốn đăng xuất?", new String[]{"Đăng xuất", "Không"});
        if (ch==0) {
            Application.ACCOUNT=null;
            this.setVisible(false);
            new LoginScreen().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        setViewPort(new StudentFrame());
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        JDialog dia = new JDialog(this, "Hướng dẫn sử dụng", true);
        JLabel lblHelp = new JLabel(readHelpFile());
        JScrollPane scrHelp = new JScrollPane(lblHelp);
        dia.setLayout(new CardLayout());
        dia.getContentPane().add(scrHelp);
        dia.setSize(WindowSize.SMALL_WINDOW.getDimension());
        dia.setLocationRelativeTo(this);
        dia.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem chkApp;
    private javax.swing.JCheckBoxMenuItem chkWeb;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem mniAdminAccount;
    private javax.swing.JMenuItem mniTeacherAccount;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuClass;
    private javax.swing.JMenu mnuStudent;
    private javax.swing.JMenu mnuTeacher;
    static final javax.swing.JPanel pnlViewPort = new javax.swing.JPanel();
    private javax.swing.JScrollPane scrViewPort;
    // End of variables declaration//GEN-END:variables

    private void initContext() {
        JMenuItem mni;
        // Title bar & Windows
        if (Application.ACCOUNT != null) {
            setTitle(getTitle() + " [" + Application.ACCOUNT.getId() + "]");
        }
        setLocationRelativeTo(null);
    }

    static void setViewPort(JPanel panel) {
        pnlViewPort.setVisible(false);
        pnlViewPort.removeAll();
        pnlViewPort.add(panel);
        pnlViewPort.repaint();
        pnlViewPort.revalidate();
        pnlViewPort.updateUI();
        pnlViewPort.setVisible(true);
    }
    
    private String readHelpFile() {
        String r="";
        File f = new File("UserManual-Manager.html");
        try {
            if (!f.exists()) {
                return r;
            }
            r = new String(Files.readAllBytes(f.toPath()));
        } catch (IOException ex) {
            // ignore
        }
        return r;
    }

    private void applyRealms() {
        String[] realms = Application.ACCOUNT.getProhibited().split(",");
        for (String r : realms) {
            switch(r) {
                case "class":
                    mnuClass.setVisible(false);
                    break;
                case "student":
                    mnuStudent.setVisible(false);
                    break;
                case "teacher":
                    mnuTeacher.setVisible(false);
                    break;
                case "admin":
                    mnuAdmin.setVisible(false);
                    mniAdminAccount.setVisible(false);
                    mniTeacherAccount.setVisible(false);
                    break;
                default:
                    // do nothing
                    break;
            }
        }
    }
}
