/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.classes;

import com.client.manager.constants.WebMethods;
import com.client.manager.constants.WindowSize;
import com.client.manager.dto.BulkDTO;
import com.client.manager.dto.TeacherDTO;
import com.client.service.Bulk;
import com.client.service.Teacher;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Giang
 */
public class AddClassFrame extends javax.swing.JPanel {
    private List<Bulk> bulk;
    private List<BulkDTO> bulkList = new ArrayList<>();
    private List<Teacher> teacher;
    private List<TeacherDTO> teachersList = new ArrayList<>();
    private DefaultComboBoxModel mBulk, mTeacher;

    /**
     * Creates new form AddClassFrame
     */
    public AddClassFrame() {
        initComponents();
        initData();
    }

    public AddClassFrame(List<Bulk> bulk, List<Teacher> teacher) {
        this.bulk = bulk;
        this.teacher = teacher;
        initComponents();
        initComboBox();
    }
    
    public static void showDialog(JFrame owner) {
        JDialog dia = new JDialog(owner, "Thêm lớp học", true);
        dia.setSize(WindowSize.SMALL_WINDOW.getDimension());
        dia.setResizable(false);
        dia.setLocationRelativeTo(owner);
        dia.add(new AddClassFrame());
        dia.setVisible(true);
    }
    
    public static void showDialog(JFrame owner, List<Bulk> bulk, List<Teacher> teacher) {
        JDialog dia = new JDialog(owner, "Thêm lớp học", true);
        dia.setSize(WindowSize.SMALL_WINDOW.getDimension());
        dia.setResizable(false);
        dia.setLocationRelativeTo(owner);
        dia.add(new AddClassFrame(bulk, teacher));
        dia.setVisible(true);
    }
    
    private void initData() {
        mBulk = (DefaultComboBoxModel) cboBulk.getModel();
        mBulk.removeAllElements();
        mTeacher = (DefaultComboBoxModel) cboTeacher.getModel();
        mTeacher.removeAllElements();
        
        new Thread(()->{
        // Load bulk
            List<Bulk> bulks = WebMethods.getBulks();
            for (Bulk b : bulks) {
                mBulk.addElement(new BulkDTO(b));
                bulkList.add(new BulkDTO(b));
            }
            // Load Teacher
            List<Teacher> teachers = WebMethods.getTeachers();
            for (Teacher t : teachers) {
                mTeacher.addElement(new TeacherDTO(t));
                teachersList.add(new TeacherDTO(t));
            }    
            
            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboBulk = new javax.swing.JComboBox<>();
        cboTeacher = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();

        jLabel1.setText("Tên lớp:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Khối:");

        jLabel3.setText("GV chủ nhiệm:");

        cboBulk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboBulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBulkActionPerformed(evt);
            }
        });

        cboTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTeacherActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Thêm lớp");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTeacher, 0, 285, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboBulk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboBulk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboBulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBulkActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboBulkActionPerformed

    private void cboTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTeacherActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddClassFrame c = new AddClassFrame(bulk, teacher);
        
        
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cboBulk;
    private javax.swing.JComboBox<String> cboTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void initComboBox() {
    }
}
