/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.classes;

import com.client.manager.constants.WebMethods;
import com.client.manager.constants.WindowUtility;
import com.client.manager.dto.BulkDTO;
import com.client.manager.dto.SubjectDTO;
import com.client.manager.views.LoadingScreen;
import com.client.service.Bulk;
import com.client.service.Subject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phương Nam
 */
public class BulkFrame extends javax.swing.JPanel {

    private List<BulkDTO> bulkList = new ArrayList<>();
    private List<SubjectDTO> subjects = new ArrayList<>();
    private BulkDTO current;
    private DefaultListModel mBulk;
    private DefaultTableModel mSubjects;

    /**
     * Creates new form BulkFrame
     */
    public BulkFrame() {
        initComponents();
        mSubjects = (DefaultTableModel) tblSubject.getModel();
        mSubjects.setRowCount(0);
        mBulk = new DefaultListModel();
        lstBulk.setModel(mBulk);
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBulk = new javax.swing.JList<>();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        lblNote = new javax.swing.JLabel();
        txtInfo = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        btnAdd.setText("Thêm mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lstBulk.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBulkValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstBulk);

        lblName.setText("Tên:");

        lblSubject.setText("Môn học:");

        tblSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(false), null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lựa Chọn", "Môn học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSubject.setShowVerticalLines(false);
        tblSubject.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblSubject);

        lblNote.setText("Ghi chú:");

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Lưu thay đổi");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNote)
                                .addGap(19, 19, 19))
                            .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                        .addComponent(btnSave))
                                    .addComponent(txtInfo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSubject)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNote)
                                    .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDelete)
                                    .addComponent(btnSave)))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = WindowUtility.showInputPrompt(this, "Thêm khối", "Tên khối:");
        if (name==null) {
            return;
        }
        if (name.length() < 2) {
            WindowUtility.showMessage(this, "Sửa thông tin khối", "Tên khối quá ngắn", WindowUtility.DEFAULT);
            return;
        }
        Bulk b = new Bulk();
        b.setName(name);
        b.setInfo("");
        WebMethods.addBulk(b, new ArrayList<Subject>());
        initData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().length() < 2) {
            WindowUtility.showMessage(this, "Sửa thông tin khối", "Tên khối quá ngắn", WindowUtility.DEFAULT);
            return;
        }
        current.setName(txtName.getText());
        current.setInfo(txtInfo.getText());
        ArrayList<Subject> subList = new ArrayList<>();
        for (int i = 0; i < tblSubject.getRowCount(); i++) {
            if (mSubjects.getValueAt(i, 0).equals(Boolean.TRUE)) {
                subList.add(subjects.get(i).getSubject());
            }
        }
        new Thread(() -> {
            LoadingScreen load = new LoadingScreen("Xin chờ...");
            load.setVisible(true);
            WebMethods.updateBulk(current.getBulk(), subList);
            load.dispose();
            initData();
        }).start();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lstBulkValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstBulkValueChanged
        // TODO add your handling code here:
        if (lstBulk.getSelectedIndex() >= 0) {
            current = (BulkDTO) mBulk.getElementAt(lstBulk.getSelectedIndex());
            txtName.setText(current.getName());
            txtInfo.setText(current.getInfo());
            for (int i = 0; i < tblSubject.getRowCount(); i++) {
                mSubjects.setValueAt(Boolean.FALSE, i, 0);
                for (Subject s : current.getSubjectList()) {
                    if (s.getName().equals(mSubjects.getValueAt(i, 1).toString())) {
                        mSubjects.setValueAt(Boolean.TRUE, i, 0);
                    }
                }
            }
            btnSave.setEnabled(true);
            btnDelete.setEnabled(true);
        }
    }//GEN-LAST:event_lstBulkValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JList<String> lstBulk;
    private javax.swing.JTable tblSubject;
    private javax.swing.JTextField txtInfo;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        new Thread(() -> {
            //load khối
            mBulk.removeAllElements();
            List<Bulk> bulks = WebMethods.getBulks();
            for (Bulk b : bulks) {
                mBulk.addElement(new BulkDTO(b));
            }

            //load môn học
            mSubjects.setRowCount(0);
            List<Subject> results = WebMethods.getSubjects();
            for (Subject s : results) {
                subjects.add(new SubjectDTO(s));
                mSubjects.addRow(new Object[]{false, s.getName()});
            }
        }).start();
    }
}
