/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.classes;

import com.client.manager.constants.WebMethods;
import com.client.manager.constants.WindowUtility;
import com.client.manager.dto.BulkDTO;
import com.client.manager.dto.ClazzDTO;
import com.client.manager.dto.TeacherDTO;
import com.client.manager.views.LoadingScreen;
import com.client.service.Bulk;
import com.client.service.Clazz;
import com.client.service.Teacher;
import com.marksmana.info.SingleInformation;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phương Nam
 */
public class ClassFrame extends javax.swing.JPanel {

    private ClazzDTO clazz;
    private List<TeacherDTO> teachersList = new ArrayList<>();
    private List<ClazzDTO> clazzList = new ArrayList<>();
    private List<BulkDTO> bulkList = new ArrayList<>();
    private Teacher teacher;
    private DefaultTableModel mInfo;
    private DefaultComboBoxModel mBulk, mTeacher;
    private DefaultListModel mClass;

    /**
     * Creates new form ClassFrame
     */
    public ClassFrame() {
        initComponents();
        initData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstClass = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        cboBulk = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        lblChairman = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        btnAddInfo = new javax.swing.JButton();
        btnAddClass = new javax.swing.JButton();
        btnRemoveInfo = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cboTeacher = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        lstClass.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item1", "Item2", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstClass.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstClassValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstClass);

        jLabel1.setText("Khối:");

        lblName.setText("Tên:");

        cboBulk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Khối --", " " }));

        lblChairman.setText("Chủ nhiệm:");

        lblNote.setText("Ghi chú:");

        tblInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Thông tin", "Giá trị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInfo.getTableHeader().setReorderingAllowed(false);
        tblInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInfo);

        btnAddInfo.setText("+");
        btnAddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInfoActionPerformed(evt);
            }
        });

        btnAddClass.setText("Thêm mới");
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });

        btnRemoveInfo.setText("-");
        btnRemoveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveInfoActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Lưu thay đổi");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cboTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chủ nhiệm --" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(btnAddClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblChairman))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboBulk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(cboTeacher, 0, 312, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRemoveInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddClass)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cboBulk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblChairman)
                                    .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNote)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoveInfo)
                                        .addGap(0, 80, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDelete)
                                    .addComponent(btnSave)))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfoMouseClicked
        // TODO add your handling code here:
        if (tblInfo.getSelectedRow() >= 0) {
            btnRemoveInfo.setEnabled(true);
        } else {
            btnRemoveInfo.setEnabled(false);
        }
    }//GEN-LAST:event_tblInfoMouseClicked

    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        // TODO add your handling code here:
        AddClassFrame.showDialog(null);
        // Reload class list
        initData();
    }//GEN-LAST:event_btnAddClassActionPerformed

    private void btnRemoveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveInfoActionPerformed
        // TODO add your handling code here:
        mInfo.removeRow(tblInfo.getSelectedRow());
        btnRemoveInfo.setEnabled(false);
    }//GEN-LAST:event_btnRemoveInfoActionPerformed

    private void btnAddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInfoActionPerformed
        // TODO add your handling code here:
        mInfo.addRow(new String[]{"", ""});
    }//GEN-LAST:event_btnAddInfoActionPerformed

    private void lstClassValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstClassValueChanged
        // TODO add your handling code here:
        if (lstClass.getSelectedIndex() < 0) {
            return;
        }
        clazz = (ClazzDTO) mClass.getElementAt(lstClass.getSelectedIndex());
        loadForm();
    }//GEN-LAST:event_lstClassValueChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (clazz.getId()!=1) {
            // Delete class
            int result = WebMethods.removeClass(clazz.getId());
            if (result>0) {
                initData();
                resetForm();
            } else {
                WindowUtility.showMessage(this, "Lỗi", "Có lỗi xảy ra khi xóa lớp học.", WindowUtility.ERROR);
            }
        } else {
            WindowUtility.showMessage(this, "Xóa lớp học", "Không thể lớp học lưu trữ!", WindowUtility.WARNING);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnAddInfo;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRemoveInfo;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboBulk;
    private javax.swing.JComboBox<String> cboTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChairman;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JList<String> lstClass;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        mInfo = (DefaultTableModel) tblInfo.getModel();
        mInfo.setRowCount(0);
        btnRemoveInfo.setEnabled(false);
        txtName.setText("");
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    private void initData() {
        mClass = new DefaultListModel();
        lstClass.setModel(mClass);
        mBulk = (DefaultComboBoxModel) cboBulk.getModel();
        mBulk.removeAllElements();
        mTeacher = (DefaultComboBoxModel) cboTeacher.getModel();
        mTeacher.removeAllElements();

        new Thread(() -> { // Lambda expression
            LoadingScreen load = new LoadingScreen("Đang tải...");
            load.setVisible(true);
            // Load class
            List<Clazz> classes = WebMethods.getClasses();
            for (Clazz c : classes) {
                mClass.addElement(new ClazzDTO(c));
                clazzList.add(new ClazzDTO(c));
            }
            // Load bulk
            List<Bulk> bulks = WebMethods.getBulks();
            for (Bulk b : bulks) {
                mBulk.addElement(new BulkDTO(b));
                bulkList.add(new BulkDTO(b));
            }
            // Load Teacher
            List<Teacher> teachers = WebMethods.getTeachers();
            for (Teacher t : teachers) {
                mTeacher.addElement(new TeacherDTO(t));
                teachersList.add(new TeacherDTO(t));
            }
            // end
            load.dispose();
        }).start();
    }

    private void loadForm() {
        mInfo.setRowCount(0);
        txtName.setText(clazz.getName());
        for (int i = 0; i < bulkList.size(); i++) {
            if (bulkList.get(i).getId()==clazz.getBulkId().getId()) {
                cboBulk.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < teachersList.size(); i++) {
            if (teachersList.get(i).getId()==clazz.getTeacherId().getId()) {
                cboTeacher.setSelectedIndex(i);
                break;
            }
        }
        try {
            for (SingleInformation si : clazz.getInfo()) {
                mInfo.addRow(new String[]{si.getKey(), si.getValue()});
            }
        } catch (Exception ex) {
            // ignore
        }
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
    }
}
