/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.classes;

import com.client.manager.views.LoadingScreen;
import javax.swing.JScrollPane;

/**
 *
 * @author Phương Nam
 */
public class ClassBulkFrame extends javax.swing.JPanel {

    private static JScrollPane scr1 = null, scr2 = null;

    /**
     * Creates new form ClassBulkFrame
     */
    public ClassBulkFrame(int index) {
        initComponents();
        initTabs(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain.setToolTipText("");
        tabMain.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTabs(int index) {
        new Thread(() -> {
            LoadingScreen load = new LoadingScreen("Xin chờ...");
            load.setVisible(true);

            if (scr1 == null || scr2 == null) {
                scr1 = new JScrollPane(new BulkFrame());
                scr2 = new JScrollPane(new ClassFrame());
            }
            
            tabMain.removeAll();
            tabMain.add("Khối", scr1);
            tabMain.add("Lớp học", scr2);
            tabMain.setSelectedIndex(index);

            load.dispose();
        }).start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTabbedPane tabMain = new javax.swing.JTabbedPane();
    // End of variables declaration//GEN-END:variables
}
