/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.system;

import com.client.manager.Application;
import com.marksmana.info.Information;
import com.marksmana.info.SingleInformation;
import com.marksmana.utils.Json;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuongUD
 */
public class SystemInfoFrame extends javax.swing.JPanel {

    private DefaultTableModel mInfo;

    /**
     * Creates new form SystemInfoFrame
     */
    public SystemInfoFrame() {
        initComponents();
        btnRemoveInfo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDateFormat = new javax.swing.JLabel();
        txtDateFormat = new javax.swing.JTextField();
        btnHelp = new javax.swing.JButton();
        lblDayFormat = new javax.swing.JLabel();
        txtDayFormat = new javax.swing.JTextField();
        btnHelpp = new javax.swing.JButton();
        lblHSCN = new javax.swing.JLabel();
        spin = new javax.swing.JSpinner();
        lblInfo = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemoveInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        btnApply = new javax.swing.JButton();
        spr = new javax.swing.JSeparator();
        lblTTHT = new javax.swing.JLabel();
        chbWebsite = new javax.swing.JCheckBox();
        chbPMGV = new javax.swing.JCheckBox();
        btnApplyy = new javax.swing.JButton();

        lblDateFormat.setText("Định dạng ngày:");

        txtDateFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateFormatActionPerformed(evt);
            }
        });

        btnHelp.setText("?");

        lblDayFormat.setText("Định dạng giờ:");

        txtDayFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayFormatActionPerformed(evt);
            }
        });

        btnHelpp.setText("?");
        btnHelpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelppActionPerformed(evt);
            }
        });

        lblHSCN.setText("Hệ số cao nhất");

        lblInfo.setText("Thông tin khác:");

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemoveInfo.setText("-");
        btnRemoveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveInfoActionPerformed(evt);
            }
        });

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Thông tin", "Dữ liệu"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        btnApply.setText("Áp dụng");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblTTHT.setText("Tình trạng hệ thống");

        chbWebsite.setText("Website");

        chbPMGV.setText("Phần mềm giáo viên");
        chbPMGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPMGVActionPerformed(evt);
            }
        });

        btnApplyy.setText("Áp dụng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblHSCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDayFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateFormat, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDateFormat)
                                            .addComponent(txtDayFormat))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnHelpp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chbWebsite)
                                .addComponent(lblTTHT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd)
                                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemoveInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnApplyy))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(chbPMGV)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateFormat)
                    .addComponent(txtDateFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDayFormat)
                    .addComponent(txtDayFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHSCN)
                    .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveInfo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTTHT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbWebsite)
                    .addComponent(chbPMGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApplyy)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFormatActionPerformed

    private void txtDayFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayFormatActionPerformed

    private void btnHelppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelppActionPerformed

    private void chbPMGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPMGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPMGVActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        mInfo.addRow(new String[]{"", ""});
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveInfoActionPerformed
        // TODO add your handling code here:
        mInfo.removeRow(tblInfo.getSelectedRow());
        btnRemoveInfo.setEnabled(false);
    }//GEN-LAST:event_btnRemoveInfoActionPerformed
    private void tblInfoMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (tblInfo.getSelectedRow() >= 0) {
            btnRemoveInfo.setEnabled(true);
        } else {
            btnRemoveInfo.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnApplyy;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHelpp;
    private javax.swing.JButton btnRemoveInfo;
    private javax.swing.JCheckBox chbPMGV;
    private javax.swing.JCheckBox chbWebsite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateFormat;
    private javax.swing.JLabel lblDayFormat;
    private javax.swing.JLabel lblHSCN;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTTHT;
    private javax.swing.JSpinner spin;
    private javax.swing.JSeparator spr;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtDateFormat;
    private javax.swing.JTextField txtDayFormat;
    // End of variables declaration//GEN-END:variables

}
