/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.manager.views.system;

import com.client.manager.Application;
import com.client.manager.constants.WebMethods;
import com.client.service.Properties;
import com.marksmana.info.Information;
import com.marksmana.info.SingleInformation;
import com.marksmana.utils.Json;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuongUD
 */
public class SystemInfoFrame extends javax.swing.JPanel {

    private DefaultTableModel mInfo;

    /**
     * Creates new form SystemInfoFrame
     */
    public SystemInfoFrame() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDateFormat = new javax.swing.JLabel();
        txtDateFormat = new javax.swing.JTextField();
        btnHelp = new javax.swing.JButton();
        lblTimeFormat = new javax.swing.JLabel();
        txtTimeFormat = new javax.swing.JTextField();
        btnHelpp = new javax.swing.JButton();
        lblHighestCoefficient = new javax.swing.JLabel();
        snrHighestCoefficient = new javax.swing.JSpinner();
        btnApply = new javax.swing.JButton();
        spr = new javax.swing.JSeparator();
        lblSystemStatus = new javax.swing.JLabel();
        cbxWebStatus = new javax.swing.JCheckBox();
        cbxAppStatus = new javax.swing.JCheckBox();
        btnApplyy = new javax.swing.JButton();

        lblDateFormat.setText("Định dạng ngày:");

        txtDateFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateFormatActionPerformed(evt);
            }
        });

        btnHelp.setText("?");

        lblTimeFormat.setText("Định dạng giờ:");

        txtTimeFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeFormatActionPerformed(evt);
            }
        });

        btnHelpp.setText("?");
        btnHelpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelppActionPerformed(evt);
            }
        });

        lblHighestCoefficient.setText("Hệ số cao nhất");

        snrHighestCoefficient.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        btnApply.setText("Áp dụng");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblSystemStatus.setText("Tình trạng hệ thống");

        cbxWebStatus.setText("Website");
        cbxWebStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxWebStatusActionPerformed(evt);
            }
        });

        cbxAppStatus.setText("Phần mềm giáo viên");
        cbxAppStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAppStatusActionPerformed(evt);
            }
        });

        btnApplyy.setText("Áp dụng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHighestCoefficient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTimeFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateFormat, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(snrHighestCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateFormat)
                                    .addComponent(txtTimeFormat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHelpp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(spr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbxWebStatus)
                                .addComponent(lblSystemStatus))
                            .addComponent(btnApplyy)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(cbxAppStatus)))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateFormat)
                    .addComponent(txtDateFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeFormat)
                    .addComponent(txtTimeFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHighestCoefficient)
                    .addComponent(snrHighestCoefficient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSystemStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxWebStatus)
                    .addComponent(cbxAppStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApplyy)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFormatActionPerformed

    private void txtTimeFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeFormatActionPerformed

    private void btnHelppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelppActionPerformed

    private void cbxAppStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAppStatusActionPerformed
        if (cbxAppStatus.isSelected()) {
            
        } else {
        }
    }//GEN-LAST:event_cbxAppStatusActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        String dateFmt = txtDateFormat.getText();
        String timeFmt = txtTimeFormat.getText();
        String highCoeff = snrHighestCoefficient.getValue().toString();
        Properties p = new Properties();
        p.setKey("date_format");
        p.setValue(dateFmt);
        p.setKey("time_format");
        p.setValue(timeFmt);
        p.setKey("coeff");
        p.setValue(highCoeff);

        WebMethods.updateProperty(p);
    }//GEN-LAST:event_btnApplyActionPerformed

    private void cbxWebStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxWebStatusActionPerformed
        // TODO add your handling code here:
        if (cbxWebStatus.isSelected()) {

            // do something...
        } else {

            // do something else...
        }
    }//GEN-LAST:event_cbxWebStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnApplyy;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnHelpp;
    private javax.swing.JCheckBox cbxAppStatus;
    private javax.swing.JCheckBox cbxWebStatus;
    private javax.swing.JLabel lblDateFormat;
    private javax.swing.JLabel lblHighestCoefficient;
    private javax.swing.JLabel lblSystemStatus;
    private javax.swing.JLabel lblTimeFormat;
    private javax.swing.JSpinner snrHighestCoefficient;
    private javax.swing.JSeparator spr;
    private javax.swing.JTextField txtDateFormat;
    private javax.swing.JTextField txtTimeFormat;
    // End of variables declaration//GEN-END:variables

    private void initData() {

        try {
            txtDateFormat.setText(Application.PROP.get("date_format").toString());
            txtTimeFormat.setText(Application.PROP.get("time_format").toString());
            
//            cbxWebStatus.setSelected(Application.PROP.get("web_status"));
//            cbxAppStatus.setSelected(Application.PROP.get("app_status"));
        } catch (Exception e) {
        }
    }

}
